<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

namespace Cart;
require_once(__DIR__ . '/currency.0.kamod.php');
class Currency extends \extension\ka_extensions\library\Cart\Currency {
}