<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

require_once(__DIR__ . '/controllercommoncolumnleft.0.kamod.php');
class ControllerCommonColumnLeft extends \extension\ka_extensions\mod1\ControllerCommonColumnLeft {
}