<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

require_once(__DIR__ . '/controllercommonheader.0.kamod.php');
class ControllerCommonHeader extends \extension\ka_extensions\ControllerCommonHeader {
}