<?php
/*
	This stub file was generated by kamod. You can find parent files in the same directory.
	More information can be found at https://www.ka-station.com/kamod
*/

require_once(__DIR__ . '/controllerstartuppermission.0.kamod.php');
class ControllerStartupPermission extends \extension\ka_extensions\ControllerStartupPermission {
}